name: Benchmark

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          job-summary: 'true'
